### PR TITLE
Assorted fixes

### PR DESCRIPTION
**Pull request by itscoretf**
Could definitely use a better solution, pinning it, etc. The value was previously at 20 which caused this (https://imconnor.xyz/images/cu95vvtuukbs.png)

### CODE REVIEW

**Comment by CriticalFlaw** [comment]
I'm trying to remember why it was changed. Could have been an accident. Have you tested it in all comp gamemodes?

**Comment by itscoretf** [comment]
Not currently, but I've done up some other fixes as well so I'll update this PR with the new commit and what was changed, and will test the timer in KOTH/Stopwatch soon.

**Comment by itscoretf** [comment]
Summary of the changes:

- 982f291 changes the medic secondary names in targetID to fix ridiculously long item names widening targetID. This also includes building data and some others, but pretty much the only one that will ever be seen is the Medigun (UberCharge) anyway.
- c677f5d makes the shadow for the player name consistent with larger text in other areas of the HUD.
- aa2cb19 is just a simple comment for whoever needs to move the control point icon for lower third sponsor graphics (eg. DreamHack Community Clash atm)
- d102177 is only an assumption, but I believe these were mistakenly removed or just not fixed when moving to CE health bars maybe? Either way fixed the HealthLow colour animations so they now appear in targetID and on the player panels.
- 5f54113 this one is a bit hard to test as (correct me if I'm wrong) should only move the overtime label within Control Point formats, and for now I have just moved it out of the way of the little event info / map info bar underneath the timer on ETF's web overlays.
- 8adf931 This one contains a lot more fixes:
  - Fixed alignment of many elements in this area of the HUD, some by adjusting the size slightly or the position, others by pinning those elements to something else around them.
  - Fixed the spacing between elements such as the Loadout icons & Status Effect icons, moved text for the weapon chargebars to properly align with everything else.
  - Separated the "Panel Bottom" element into one for each side, just to make pinning other elements easier (I'm not very fluent with it).
  - _Panel Bottom no longer goes underneath the class image_, but I have tried to get the transparency / darkness of the classimagebg element to be as close as possible to what it was.

Believe I've listed everything, but feel free to @ me if there is something I missed. I'll get back to you when I am 100% sure the timer changes work everywhere as intended.

**Comment by itscoretf** [comment]
@CriticalFlaw, is there a reason the damage numbers, along with the number on the control point icon (mainly in KOTH) when the point is counting down / unlocking, are in the default TF2 font rather than the one the rest of the HUD uses?

**Comment by itscoretf** [comment]
Sorry there is a bit to unpack.

- Hidden the Overtime label as it just wasn't visible in the KOTH HUD anyway, and is in an odd position in the CP HUD. 
- Added clearer point possession indicator for KOTH (https://imconnor.xyz/images/7gelisn4n8in.png).
- Updated `chat_english` with win reasons, can be edited to better suit the gamemode and whatnot.

**Comment by CriticalFlaw** [comment]
- 982f291d13bcee7e9c93809ac45081f96b0f78a0 - looks good.
- c677f5dfcd166c85bb5c71d0d2b6f91d9f51e665 - I would keep the `-2` shadows and update others to match wherever the text is big enough to not make the shadow too distracting.
   - winpanel.res in particular could use that change, along with replacing use of `Roboto16` with `RobotoBold16`.
- aa2cb194f73c5acb3aac1552e35d4b53a01db4c5 - makes sense, good idea.
- d102177842633625820b4558110a3d3ce1869568 - I don't remember either, may have been a on the whim change during one of the broadcasts or a one-off that never got reverted back. Good to add it back.
- 8adf931486f586989ab76266aeee24a81afcd6cb - looks good, I also like the new KOTH possession change.
- 5f5411364d7dbdde4dedc61e2083b7529e93bdd9 - I did some digging around and found that the overtime label is out of bounds somehow when on KOTH. If you reinstate `OvertimeLabel` and change the ypos to 8 you'll get this:
image
I suppose removing the label would eliminate the need to wrestle it into being positioned properly but at some point, the question will come up where it is, since all other spec HUDS have it. If you want to take another crack at it, we can remove it for now, create a ticket to reimplement it and handle it in a separate PR.

**Comment by CriticalFlaw** [comment]
@itscoretf need your thoughts on the below, then we can merge. Cheers and thanks for the help.
- Update the winpanel and any other locations with large text that use pinned shadows to use `-2` instead of `-1`.
- Decide on how to approach the overtime label for all gamemodes. Keep as-is or remove it for now and reimplement later.

**Comment by itscoretf** [comment]
Can modify the text in the winpanel to have the -2 shadow sure. My concern with the overtime label at the moment is its position in 5CP/CP when it is reinstated for KOTH, I'm not entirely sure how to have it in the correct position and work for both but can look into it.

I'll put those changes up now so it can be merged.

**Comment by itscoretf** [comment]
@CriticalFlaw Should be good to go.

**Comment by CriticalFlaw** [comment]
Looks great. Thank you so much for the work.

**Pull request merged**
